### ISSUE TITLE
Cannot fit with the model ViT

### ISSUE THREAD

**Issue by DRedflag** [taki0112/vit-tensorflow#4]
```
 v = ViT(
    image_size = 256,
    patch_size = 32,
    num_classes = 4,
    dim = 1024,
    depth = 6,
    heads = 16,
    mlp_dim = 2048,
    dropout = 0.1,
    emb_dropout = 0.1
)
img = tf.random.normal(shape=[1, 256, 256, 3])
preds = v(img) # (1, 1000)

train_set = tf.keras.utils.image_dataset_from_directory("/content/data/train", image_size=(256,256), batch_size=32, interpolation='bicubic', label_mode="categorical")
val_set = tf.keras.utils.image_dataset_from_directory("/content/data/valid", image_size=(256,256), batch_size=32, interpolation='bicubic', label_mode="categorical", shuffle=False)

v.compile(loss=tf.keras.losses.CategoricalCrossentropy(), 
            optimizer=tf.keras.optimizers.Adam(),
            metrics=["acc"])

v.fit(train_set, validation_data=val_set, batch_size=32, epochs=100, verbose=1
```
give this error

```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-17-f5c08ebc8cc3>](https://localhost:8080/#) in <module>
----> 1 v.fit(train_set, validation_data=val_set, batch_size=32, epochs=100, verbose=1)

7 frames

[/usr/local/lib/python3.8/dist-packages/einops/einops.py](https://localhost:8080/#) in _product(sequence)
     34     result = 1
     35     for element in sequence:
---> 36         result *= element
     37     return result
     38 

TypeError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 889, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_filerxhk6fus.py", line 12, in tf__call
        cls_tokens = ag__.converted_call(ag__.ld(repeat), (ag__.ld(self).cls_token, '() n d -> b n d'), dict(b=ag__.ld(b)), fscope)
    File "/tmp/__autograph_generated_fileijtzgzuy.py", line 13, in tf__repeat
        retval_ = ag__.converted_call(ag__.ld(reduce), (ag__.ld(tensor), ag__.ld(pattern)), dict(reduction='repeat', **ag__.ld(axes_lengths)), fscope)
    File "/tmp/__autograph_generated_file_lullqmi.py", line 16, in tf__reduce
        retval_ = ag__.converted_call(ag__.ld(_apply_recipe), (ag__.ld(recipe), ag__.ld(tensor)), dict(reduction_type=ag__.ld(reduction)), fscope)
    File "/tmp/__autograph_generated_fileb28zil2f.py", line 11, in tf___apply_recipe
        (init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes) = ag__.converted_call(ag__.ld(_reconstruct_from_shape), (ag__.ld(recipe), ag__.converted_call(ag__.ld(backend).shape, (ag__.ld(tensor),), None, fscope)), None, fscope)
    File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 217, in _reconstruct_from_shape_uncached
        final_shapes.append(_product(lengths))
    File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 36, in _product
        result *= element

    TypeError: Exception encountered when calling layer "vi_t" (type ViT).
    
    in user code:
    
        File "<ipython-input-3-49dad1abd119>", line 153, in call  *
            cls_tokens = repeat(self.cls_token, '() n d -> b n d', b=b)
        File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 533, in repeat  *
            return reduce(tensor, pattern, reduction='repeat', **axes_lengths)
        File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 412, in reduce  *
            return _apply_recipe(recipe, tensor, reduction_type=reduction)
        File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 234, in _apply_recipe  *
            init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes =         _reconstruct_from_shape(recipe, backend.shape(tensor))
        File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 217, in _reconstruct_from_shape_uncached  **
            final_shapes.append(_product(lengths))
        File "/usr/local/lib/python3.8/dist-packages/einops/einops.py", line 36, in _product
            result *= element
    
        TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
    
    
    Call arguments received by layer "vi_t" (type ViT):
      • img=tf.Tensor(shape=(None, 256, 256, 3), dtype=float32)
      • training=True
      • kwargs=<class 'inspect._empty'>
```
Can some one help?

**Comment by JasonYangCode** [comment]
from vit_tensorflow.vit import ViT

**Comment by Deewens** [comment]
Hi, I have the same issue, how did you solve it?

**Comment by 123epsilon** [comment]
@Deewens @JasonYangCode @DRedflag 

I have the exact same issue, I think this is a batching issue as for some reason when the batch size does not divide the dataset size I get this issue, I was able to overcome it with a snippet like this:

```
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import optimizers
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.datasets import cifar10
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

(train_data, train_label), (test_data, test_label) = cifar10.load_data()
train_label = to_categorical(train_label)
test_label = to_categorical(test_label)
train_data = (train_data/255.).astype("float32")
test_data = (test_data/255.).astype("float32")

X_train, X_valid, y_train, y_valid = train_test_split(train_data, train_label, shuffle=True)

batch_size = 256
datagen = ImageDataGenerator(rotation_range=15, width_shift_range=0.2, zoom_range=0.2, horizontal_flip=True)
train_generator = datagen.flow(X_train, y_train, batch_size=batch_size)

model = ViT(
    image_size = 32,
    patch_size = 4,
    num_classes = 10,
    dim = 512,
    depth = 6,
    heads = 8,
    mlp_dim = 512,
    dropout = 0.1,
    emb_dropout = 0.1
)

num_epochs = 100
cosine_decay_scheduler = tf.keras.optimizers.schedules.CosineDecay(
    0.01, num_epochs, alpha=0.0, name=None
)

optimizer = tf.keras.optimizers.Adam(learning_rate=cosine_decay_scheduler)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"], run_eagerly=True)
model.fit(train_generator, batch_size=256, epochs=num_epochs)

```

However, even though this doesn't throw an error this model simply doesn't seem to improve during training. This is odd, because the PyTorch equivalent (https://github.com/kentaroy47/vision-transformers-cifar10) performs very well with the same parameters. I'm not sure if I'm doing something wrong.
